stages:
  - show_dir
  - build
  - test

# ==========================================
# ИНФОРМАЦИЯ О ДИРЕКТОРИЯХ
# ==========================================
show_dir_linux:
  stage: show_dir
  script:
    - pwd
  tags:
    - Debian13Runner

show_dir_win10:
  stage: show_dir
  script:
    - Get-Location
  tags:
    - Windows10

show_dir_win11:
  stage: show_dir
  script:
    - Get-Location
  tags:
    - Windows11

# ==========================================
# СБОРКА 
# ==========================================
build-debian13:
  stage: build
  interruptible: true
  variables:
    GIT_LFS_SKIP_SMUDGE: 0
  needs: []
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Release"
        CMAKE_GENERATOR: "Unix Makefiles"
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      variables:
        CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE" 
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Release -DBUILD_DOXYGEN_DOC=ON"
        CMAKE_GENERATOR: "Unix Makefiles"
  before_script:
    - ls -la ./
    - mkdir -p build
  script:
    - cd build
    - cmake ${CMAKE_FLAGS} .. && cmake --build .
  artifacts:
    expire_in: 1 hour
    paths:
      - build/
  tags:
    - Debian13Runner 
      
build-windows10:
  stage: build
  interruptible: true
  variables:
    GIT_LFS_SKIP_SMUDGE: 0
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Release"
        CMAKE_GENERATOR: "MinGW Makefiles"
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      variables:
        CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE" 
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Release -DBUILD_DOXYGEN_DOC=ON"
        CMAKE_GENERATOR: "MinGW Makefiles"
  before_script:
    - Get-ChildItem ./                 
    - if (!(Test-Path build)) { New-Item -ItemType Directory -Force -Path build }
  script:
    - cd build
    - cmake $env:CMAKE_FLAGS "-DCMAKE_PREFIX_PATH=C:/Dev/orm_odb" .. 
    - cmake --build .
  artifacts:
    expire_in: 1 hour
    paths:
      - build/
  tags:
    - Windows10

build-windows11:
  stage: build
  interruptible: true
  variables:
    GIT_LFS_SKIP_SMUDGE: 0
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Release"
        CMAKE_GENERATOR: "MinGW Makefiles"
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      variables:
        CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE" 
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Release -DBUILD_DOXYGEN_DOC=ON"
        CMAKE_GENERATOR: "MinGW Makefiles"
  before_script:
    - Get-ChildItem ./                 
    - if (!(Test-Path build)) { New-Item -ItemType Directory -Force -Path build }
  script:
    - cd build
    - cmake $env:CMAKE_FLAGS "-DCMAKE_PREFIX_PATH=C:/Dev/orm_odb" .. 
    - cmake --build .
  artifacts:
    expire_in: 1 hour
    paths:
      - build/
  tags:
    - Windows11

# ==========================================
# ТЕСТИРОВАНИЕ 
# ==========================================
test-debian13:
  stage: test
  interruptible: true
  needs:
    - job: build-debian13 
      artifacts: true
  script:
    - cd build
    - ctest --output-on-failure 
  tags:
    - Debian13Runner

test-windows10:
  stage: test
  interruptible: true
  needs:
    - job: build-windows10 
      artifacts: true
  script:
    - if (Test-Path build) { cd build }
    - ctest --output-on-failure
  tags:
    - Windows10

test-windows11:
  stage: test
  interruptible: true
  needs:
    - job: build-windows11 
      artifacts: true
  script:
    - if (Test-Path build) { cd build }
    - ctest --output-on-failure
  tags:
    - Windows11